version: '2'
services:
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
    - PUID=1000
    - PGID=1000
    volumes:
    - /home/barry/mongodb/database:/data/db
    ports:
    - ${mongo_port}:27017
    expose: 
    - "27017"
    restart: unless-stopped
    command: mongod --quiet --logpath /dev/null
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    expose:
    - "2181"
    environment: 
      ZOO_LOG4J_PROP: "INFO,ROLLINGFILE"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
    - zookeeper
    ports:
      - "${kafka_outside_port}:${kafka_outside_port}"
    expose:
      - ${kafka_inside_port}
    logging: 
      driver: "none"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://${kafka_inside_host}:${kafka_inside_port},OUTSIDE://${kafka_outside_host}:${kafka_outside_port}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:${kafka_inside_port},OUTSIDE://0.0.0.0:${kafka_outside_port}
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: ${kafka_topic}:1:1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=WARN,kafka.producer.async.DefaultEventHandler=WARN,state.change.logger=WARN,kafka=WARN"
  web:
    build: ./rest
    container_name: restAPI
    ports: 
      - ${rest_port}:${rest_port}
    restart: always
    volumes:
      - .:/codes
    environment: 
      REST_HOST: ${rest_host}
      REST_PORT: ${rest_port}
      KAFKA_TOPIC: ${kafka_topic}
      KAFKA_ADDRESS: ${kafka_inside_host}:${kafka_inside_port}
  consumer:
    container_name: kafkaConsumer
    build : ./consumer
    restart: always
    environment: 
      KAFKA_ADDRESS: ${kafka_inside_host}:${kafka_inside_port}
      MONGO_ADDRESS: "mongodb:${mongo_port}"
      KAFKA_TOPIC: ${kafka_topic}
  dashboard:
    container_name: dashboard
    build : ./dashboard
    ports:
      - "8052:8052"
    expose: 
      - "8052"
    environment: 
      MONGO_ADDRESS: "mongodb:${mongo_port}"
      TZ: Turkey/Istanbul


  
